name: update-blacklist
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: bash scripts/update_blacklists.sh || true
      - run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git diff --quiet && exit 0
          git add data/phishtank.csv
          git commit -m "chore: weekly blacklist update"
          git push
